substitutions:
  friendly_name: Velux Remote
  device_name: velux_remote

esphome:
  name: "${device_name}"
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "fallback"
    password: "pommesmayo"

captive_portal:

# Enable logging
logger:
  
# Enable Home Assistant API
api:
  password: !secret ota_password

ota:
  password: !secret ota_password

switch:
  - platform: gpio
    id: velux_down
    pin: 13
    inverted: yes

  - platform: gpio
    id: velux_stop
    pin: 12
    inverted: yes

  - platform: gpio
    id: velux_up
    pin: 14
    inverted: yes

cover:
  - platform: template
    name: "${friendly_name}"
    open_action:
      # Cancel any previous action
      - switch.turn_off: velux_down
      # Turn the OPEN switch on briefly
      - switch.turn_on: velux_up
      - delay: 0.1s
      - switch.turn_off: velux_up
    close_action:
      - switch.turn_off: velux_up
      - switch.turn_on: velux_down
      - delay: 0.1s
      - switch.turn_off: velux_down
    stop_action:
      - switch.turn_off: velux_down
      - switch.turn_off: velux_up
      - switch.turn_on: velux_stop
      - delay: 0.1s
      - switch.turn_off: velux_stop
    optimistic: true
    assumed_state: true
